export const ACTIVITY_TAG = {
    MAIN:'MAIN',
    PREREQUISITES:'PREREQUISITES',
    HIGH_SCORE:'HIGH_SCORE',
    SETTINGS:'SETTINGS'
}

export const ACTIVITY_TITLE = {

    MAIN: 'HEAVY GADDIYA',
    PREREQUISITES: 'HEAVY GADDIYA'

}